import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Image from "next/image";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Gyznxfx7DiG
 */

export function Contact() {
  return (
    <div className="w-full py-20 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-12 lg:gap-12">
          <div className="space-y-2 lg:col-span-7">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Contact us
              </h1>
              <p className="text-gray-500 dark:text-gray-400">
                {`We'll`} get back to you as soon as possible.
              </p>
            </div>
            <div className="grid gap-4">
              <div className="space-y-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="message">Message</Label>
                <Textarea
                  className="min-h-[100px] resize-none"
                  id="message"
                  placeholder="Enter your message"
                />
              </div>
              <Button type="submit">Submit</Button>
            </div>
          </div>
          <div className="smd:flex items-center lg:col-span-5 hidden">
            <Image
              alt="Image"
              className="rounded-xl object-cover flex dark:hidden"
              height="300"
              src="/logos/2.svg"
              style={{
                aspectRatio: "600/600",
                objectFit: "cover",
              }}
              width="600"
            />
            <Image
              alt="Image"
              className="rounded-xl object-cover hidden dark:flex"
              height="300"
              src="/logos/1.svg"
              style={{
                aspectRatio: "600/600",
                objectFit: "cover",
              }}
              width="600"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
