/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vvwzpZu8qU3
 */
import Link from "next/link";
import { Meteors } from "./meteors";

export function NotFound() {
  return (
    <main className="flex flex-1 items-center justify-center w-full h-[100vh] text-center">
      <Meteors number={40} className={`absolute z-[1]`} />
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-4xl font-extrabold tracking-tighter sm:text-6xl lg:text-7xl">
            404 Error
          </h1>
          <h2 className="inline-block text-3xl font-extrabold tracking-tighter md:text-5xl lg:text-6xl/none">
            Page Not Found
          </h2>
        </div>
        <div className="mx-auto max-w-[500px] space-y-4">
          <p className="inline-block text-gray-500 text-xl font-medium tracking-wide/[-0.025] sm:text-2xl/[-0.025] md:text-base/relaxed lg:text-xl/relaxed xl:text-base/relaxed dark:text-gray-400">
            Oops! The page you are looking for does not exist.
          </p>
        </div>
        <div className="mx-auto max-w-[400px]">
          <div />
        </div>
        <div className="flex flex-col min-[300px]:flex-row mx-auto items-center justify-center space-y-2 gap-2">
          <p className="text-sm text-gray-500 sm:text-base dark:text-gray-400">
            Want to go back home?
          </p>
          <Link href="/">
            <span className="font-medium underline transition-colors hover:text-gray-900 dark:hover:text-gray-50">
              Go to the homepage
            </span>
          </Link>
        </div>
      </div>
    </main>
  );
}
