/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Eujxa85ynsP
 */

import { Meteors } from "./meteors";

export function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-3xl px-8 py-12 md:py-16 lg:py-24 lg:px-6">
      <Meteors number={40} className={`absolute z-[1]`} />
      <div className="prose prose-gray-900 dark:prose-gray-100">
        <h1
          className={`my-[30px] text-4xl font-extrabold tracking-tighter sm:text-6xl lg:text-7xl`}
        >
          Privacy Policy
        </h1>
        <p>
          Last updated: April 1, 2024. This Privacy Policy describes Our
          policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy
          rights and how the law protects You.
        </p>
        <h2 className={`text-2xl mt-[30px]`}>Interpretation and Definitions</h2>
        <h3 className={`text-md my-[10px] border-b-2`}>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3 className={`text-md mt-[30px] mb-[10px] border-b-2`}>
          Definitions
        </h3>
        <p>For the purposes of this Privacy Policy;</p>
        <ul className={`space-y-2`}>
          <li>
            <strong>You </strong>
            means the individual accessing or using the Service, or the company,
            or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </li>
          <li>
            <strong>Company </strong>
            (referred to as either {"the Company"}, {"We"}, {"Us"} or {"Our"} in
            this Agreement) refers to Science Maverick.
          </li>
          {/* <li>
            <strong>Affiliate</strong>
            means an entity that controls, is controlled by or is under common
            control with a party, where {"control"} means ownership of 50% or
            more of the shares, equity interest or other securities entitled to
            vote for election of directors or other managing authority.
          </li> */}
          <li>
            <strong>Account </strong>
            means a unique account created for You to access our Service or
            parts of our Service.
          </li>
          <li>
            <strong>Website </strong>
            refers to Science Maverick website, accessible from
            https://9qhlzz-3000.csb.app/
          </li>
          <li>
            <strong>Service </strong>
            refers to the Website.{"\n                  "}
          </li>
          <li>
            <strong>Country </strong>
            refers to: Pakistan, Asia.{"\n                  "}
          </li>
          <li>
            <strong>Service Provider </strong>
            means any natural or legal person who processes the data on behalf
            of the Company. It refers to third - party companies or individuals
            employed by the Company to facilitate the Service, to provide the
            Service on behalf of the Company, to perform services related to the
            Service or to assist the Company in analyzing how the Service is
            used.
          </li>
          <li>
            <strong>Third - party Social Media Service </strong>
            refers to any website or any social network website through which a
            User can log in or create an account to use the Service.
          </li>
          <li>
            <strong>Personal Data </strong>
            is any information that relates to an identified or identifiable
            individual.
          </li>
          <li>
            <strong>Cookies </strong>
            are small files that are placed on Your computer, mobile device or
            any other device by a website, containing the details of Your
            browsing history on that website among its many uses.
          </li>
          <li>
            <strong>Device </strong>
            means any device that can access the Service such as a computer, a
            cellphone or a digital tablet.
          </li>
          <li>
            <strong>Usage Data </strong>
            refers to data collected automatically, either generated by the use
            of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </li>
        </ul>
        <h2 className={`text-2xl mt-[30px]`}>
          Collecting and Using Your Personal Data
        </h2>
        <h3 className={`text-md mt-[10px] mb-[30px] border-b-2`}>
          Types of Data Collected
        </h3>
        <h2 className={`text-2xl mt-[30px]`}>Personal Data</h2>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="list-disc">
          <li>Email address</li>
          <li>First name and last name</li>
          {/* <li>Address, State, Province, ZIP/Postal code, City</li> */}
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>
        <h2 className={`text-2xl mt-[30px] border-t-2 pt-[10px]`}>
          Usage Data
        </h2>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p />
      </div>
    </div>
  );
}
