/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sFlZ2JR8lqP
 */
import Link from "next/link";
import { Meteors } from "./meteors";

export function TermsOfServiceComponent() {
  return (
    <div className="mx-auto mt-[50px] lg:mt-0 max-w-3xl px-4 py-12 md:py-16 lg:py-24 lg:px-6">
      <div>
        <Meteors number={40} className={`absolute z-[1]`} />
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="space-y-6">
            <div className="space-y-2">
              <h1 className="text-4xl font-extrabold tracking-tighter sm:text-6xl lg:text-7xl">
                Terms of Service
              </h1>
              <p className="text-gray-500 dark:text-gray-400">
                Last updated: April 1, 2024
              </p>
            </div>
            <div className="prose prose-gray max-w-none">
              <p>
                Welcome to our Terms of Service! These terms and conditions
                outline the rules and regulations for the use of our Company
                {`'`}s Website, located at https://9qhlzz-3000.csb.app/
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Intellectual Property
              </h2>
              <p className={`my-[10px]`}>
                Unless otherwise stated, Science Maverick and/or its licensors
                own the intellectual property rights for all material on
                https://9qhlzz-3000.csb.app/ All intellectual property rights
                are reserved. You may access this from
                https://9qhlzz-3000.csb.app/ for your own personal use subjected
                to restrictions set in these terms and conditions.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>Restrictions</h2>
              <p className={`mt-[10px]`}>
                You are specifically restricted from all of the following:
              </p>
              <ul className="list-disc">
                <li>
                  Publishing any website material in any other media without
                  citation.
                </li>
                <li>
                  Selling, sublicensing, and/or otherwise commercializing any
                  website material.
                </li>
                <li>
                  Publicly performing and/or showing any website material
                  without citation or consent.
                </li>
                <li>
                  Using this website in any way that is or may be damaging to
                  this website.
                </li>
                <li>
                  Using this website in any way that impacts user access to this
                  website.
                </li>
                <li>
                  Using this website contrary to applicable laws and
                  regulations, or in any way may cause harm to the website, or
                  to any person or business entity.
                </li>
                <li>
                  Engaging in any data mining, data harvesting, data extracting
                  or any other similar activity in relation to this website.
                </li>
              </ul>
              <p className={`mt-[30px] border-t-2`}>
                Certain areas of this website are restricted from being access
                by you and Science Maverick may further restrict access by you
                to any areas of this website, at any time, in absolute
                discretion. Any user ID and password you may have for this
                website are confidential and you must maintain confidentiality
                as well.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>Your Privacy</h2>
              <p className={`mt-[10px]`}>
                Please read our Privacy Policy. Your agreement to the terms of
                this Privacy Policy is hereby incorporated into these Terms of
                Service.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>No warranties</h2>
              <p className={`mt-[10px]`}>
                This website is provided {`"as is,"`} with all faults, and
                Science Maverick express no representations or warranties, of
                any kind related to this website or the materials contained on
                this website. Also, nothing contained on this website shall be
                interpreted as advising you.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Limitation of liability
              </h2>
              <p className={`mt-[10px]`}>
                In no event shall Science Mavercik, nor any of its officers,
                directors, and employees, shall be held liable for anything
                arising out of or in any way connected with your use of this
                website whether such liability is under contract. Science
                Maverick, including its officers, directors, and employees shall
                not be held liable for any indirect, consequential or special
                liability arising out of or in any way related to your use of
                this website.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Indemnification
              </h2>
              <p className={`mt-[10px]`}>
                You hereby indemnify to the fullest extent Science Maverick from
                and against any and/or all liabilities, costs, demands, causes
                of action, damages and expenses arising in any way related to
                your breach of any of the provisions of these Terms.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>Severability</h2>
              <p className={`mt-[10px]`}>
                If any provision of these Terms is found to be invalid under any
                applicable law, such provisions shall be deleted without
                affecting the remaining provisions herein.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Variation of Terms
              </h2>
              <p className={`mt-[10px]`}>
                Science Maverick is permitted to revise these Terms at any time
                as it sees fit, and by using this Website you are expected to
                review these Terms on a regular basis.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Entire Agreement
              </h2>
              <p className={`mt-[10px]`}>
                These Terms constitute the entire agreement between Science
                Maverick and you in relation to your use of this Website, and
                supersede all prior agreements and understandings.
              </p>
              <h2 className={`text-2xl mt-[30px] border-b-2`}>
                Governing Law & Jurisdiction
              </h2>
              <p className={`mt-[10px]`}>
                These Terms will be governed by and interpreted in accordance
                with the laws of the State of Pakistan, and you submit to the
                non-exclusive jurisdiction of the state and federal courts
                located in Pakistan for the resolution of any disputes.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div className="flex items-center justify-center space-x-4 mt-[30px] text-sm">
          <Link
            className="font-medium hover:text-slate-700 dark:hover:text-gray-200"
            href="/terms-of-service"
          >
            Terms of Service
          </Link>
          <Link
            className="font-medium hover:text-slate-700 dark:hover:text-gray-200"
            href="/privacy-policy"
          >
            Privacy Policy
          </Link>
          <Link
            className="font-medium hover:text-slate-700 dark:hover:text-gray-200"
            href="/contact"
          >
            Contact Us
          </Link>
        </div>
      </div>
    </div>
  );
}
